language: go
go:
- 1.11.x
sudo: false
services:
- docker
notifications:
  slack:
    secure: U9KIWPdgHSOOX+iqyKkn2+u/p8i/q9hn8HSSKoK8hLXLqX++gcBJSXG9bwbLWleqaUOwJ2usR17yZabvG2+2lYBocQD8clc9agFczjsX95NNYUBTPCRtGgP906muE9d50F8kuqW6I+Ehq7i9C/kwl3t2ef/FuYtVFF+Vw+e/AxYs+kPobwIBCeMPHYMbK0dSRrabIvKfkoMGtFqglj6Ak89Cxb+JLSy6T8xnDI/oRAbZtymNBPfauKMQFbuFW6GahbQ/NGRbtXCvG1iSpIM9tlCLffJSZOSG3U2j3/Djw92vV92W7hvvsKl4xqjQipV2L9kv0GwTrARpyaStP5fObM3cBA+1QAnmqoeHnMcS4rODm3YmyjMLGhEj2T3n4fGmaRK+mhESyAOl5U6iZNtP2tbBexDIlzA/1YaCDYOX6KydcFhF/fSJ5/uQy5obMg1+2UA5qfDTX37UwOftnp+yOv30YU+fF40Uec1j1HuRnkq7lLJFwoyQv8W5XBsMke1HIJbmplX4OWqkRf9Bb7r0IERpZZIwAV/qQRHBe/qUqz8IG1N9GHdnoRwTDa8sIrKKHMbLO6aMpcNICO6DJFQ7xDP6tQZeLq6lHv0T8URU7m8HwU3NaGcv8vjeK5QTq0Z/Mw6lWdR+mpxw/nzqv4cYH2xxgxZ7FJBSFKlC+n8nec4=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - GO111MODULE=on
  - secure: JqPmxPGYNAml4qmqu0z8OMOD6Ap44/9gDahZTMe0o4bHsQ6XeB3SRzrRYoTRHOwIynSDsti2Pb+2GvEH5y7aL9L3qqtMKNjfBpDWgTLpIrLS6Ir6qudwUGYqIXPKT0/vKXOJqZ+zeN3mOT8XXXkLhGK9IS7HFkuFfg2aJOIXnov/EUnRxerj+X+HS0hIpR/seMdfyRlWH+eanpwfN9W1jfRoZX5ArHv69/NKkc8rCwlSBaRHFXwXIibKsFD5o+hmQuoYZC3KmHdWfTCSFypUYwFfSxEppEMFEEINazf/Cw8uOG7MczHXwNFjf701Ebdgextbyrycwx//A6UB+sU9SNMDshUObcN8XhQpNVSC0s9JUu4pv2a1aso/PTRdRSlngnybnr5mKc0dhpzXoTIyQwNKh1or3Y4TDksi6rMnpe2Y/4I/rv3KhRfSitk1BBEcgCcGS32/eDX2IglL531LNLvArF6eORNws1LqXLba6TsxC5pkb+iS9k0TMpwkb0TFm/46bmqWIpmNsqBYxsrUK0MfSIU8xGdxaHsI5T8QQmUlFy/fKNMOKmPYPDe7qLXhZo9xauVZZ6tA7KsJghSPlqMqBK33Qof53ducXSs81iovE7b724Qb0Fpmt5qbit9niAoMXtFtbUSd+6bKUksqqll83emX6QJFmQfBopu4kXQ=
  - secure: qYZoHlVpaAKr00ag7pH5OzvgMFuxdkOo1rEh9uf2vz1uYwy7JvnScc0f5ysCSy2G2gsxnPmktsqsJo2l57c/qyiPWdKzspFp83Vp10gL6+kX84VnFK5r5W9/QIwZVu5FI/pyAr4u+TKFAqM7sgmjykzXJ3/idpe5rxGQHhBOGZQSPkhKCmgp9rLH9kb/X9Ggjh5qkYc2/m+s4Cg2bD6wdig0T+awhYySB0qo+4arhHj6i6g9lTNqIuK0WL0G6Yh9bw6YQynuTtGrhOrLUkuzvNhxEAysUVxfCoPOJIAqllVgkQ65ejGEbt5/j+MOl8Kc71/xcjXuVnyCNL88B7eEme/MxbbCnFACEPYAyUZtN+LaTKInLQoRdRgUw8mlfeTsskjENi/s2MRXpt0POc0BTR7GJnAh4D3rN1K4mVu30LRCf96b5sqT0iheCa7/LEW65PrvDqyRbGfpvAJG/blhNGvDa02q2hryGOfxIY5/jhRBKRSCoSOuIUTDbbjfGUH56GYmu5i55/Xnvw+V+BG2FgeF8TiW/Q5kefzaqw1ABbeF9XRRE2dimgB59kj+u/DBC6q5EH3vOA0oQudv4PtkLThVeuX1yDNwMp7fZD2go9wxVXLDy3zQAnNg31HCjebGM/JwMeFcJ9YPIU5XwNkHH/HUB0ovTVeVdbNRQFyIcRQ=
  - secure: IGCPJb8ajPSc+t+YoWwlbILOP+nBARwISSgZ/3X7lXVLM17jcbZuTWyj3kJwnxBEq/2/lXozqo3hqkezOBxLRYfPxE25+RHcSs/xGuxfC1YEtyqU2ycBf77MWrZ8O7qEk6OLxuvlRS4y7zsl4zzZRwPzdec2Mca4OGi7ATPAOIM58y6ueloVRRY8g3r3ryHokAQeNrorn1yf/cCfS+wM97df3TlmxdEa18JmQOJEhRIKHrMJfZyMMoNthLqILvrOJZulH+eVBrcxm4C9H/+K5V60XPnMacAIlI1x2jptPcKshb4dlyDvQtljb5bN4CuXx2oLYE0rRwv3MWcOeDXxLMkDLE2ibY6TBHi/DDkUCrw6lklWkJuoGIs/19YbAPjNWGW8Um+TGilVTz2lUMh2NRSSK/ubdjc4cxFi84XzwZEsYIwUIXk65EVzu98w2fPEQOZFg4JTnUoIq0+mdLKx8drLJ+h7N8895tGeCfP3IUanl80gdJgr+PWmPXqQxC/h0qKFciRykNnfrgNrwgqWLJ0mWwlCICVHUnCwsJY00OR85ptN31xwymQA98J54AV2XZav9hZDjwwtN3M9E49jGQ7lZ7kH4AA00H8fJhqAHfVwEH8u7ogepgZO/F/N08A89M0cgG8khYXX55yqUjug0NB6f6J+Ka/135H/h7HnVZE=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- travis version
- export BUILD_NAME=gopocservice-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
before_script:
- export GOPATH=$HOME/gopath
- export PATH=$HOME/gopath/bin:$PATH
- mkdir -p $HOME/gopath/src/github.com/anthonydenecheau/gopocservice
- rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/anthonydenecheau/gopocservice/
- export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/anthonydenecheau/gopocservice
- cd $HOME/gopath/src/github.com/anthonydenecheau/gopocservice
script:
- sh scripts/travis/travis.gofmt.sh
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
