language: go
go:
- 1.11.x
- master
sudo: false
services:
- docker
notifications:
  slack:
    secure: U9KIWPdgHSOOX+iqyKkn2+u/p8i/q9hn8HSSKoK8hLXLqX++gcBJSXG9bwbLWleqaUOwJ2usR17yZabvG2+2lYBocQD8clc9agFczjsX95NNYUBTPCRtGgP906muE9d50F8kuqW6I+Ehq7i9C/kwl3t2ef/FuYtVFF+Vw+e/AxYs+kPobwIBCeMPHYMbK0dSRrabIvKfkoMGtFqglj6Ak89Cxb+JLSy6T8xnDI/oRAbZtymNBPfauKMQFbuFW6GahbQ/NGRbtXCvG1iSpIM9tlCLffJSZOSG3U2j3/Djw92vV92W7hvvsKl4xqjQipV2L9kv0GwTrARpyaStP5fObM3cBA+1QAnmqoeHnMcS4rODm3YmyjMLGhEj2T3n4fGmaRK+mhESyAOl5U6iZNtP2tbBexDIlzA/1YaCDYOX6KydcFhF/fSJ5/uQy5obMg1+2UA5qfDTX37UwOftnp+yOv30YU+fF40Uec1j1HuRnkq7lLJFwoyQv8W5XBsMke1HIJbmplX4OWqkRf9Bb7r0IERpZZIwAV/qQRHBe/qUqz8IG1N9GHdnoRwTDa8sIrKKHMbLO6aMpcNICO6DJFQ7xDP6tQZeLq6lHv0T8URU7m8HwU3NaGcv8vjeK5QTq0Z/Mw6lWdR+mpxw/nzqv4cYH2xxgxZ7FJBSFKlC+n8nec4=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - GO111MODULE=on
  - secure: fI9W7JPIxJUBAsKac2U566jrO/90XJYTOdsAwIPkG91SWJ55D6hh4dAA7X943fkNjcl290Wo3CXcUyS5F23PRLZFjxXAN3nw8bdrwlPQeHqWzEhFiOLQVYFz0T/g7dfyym1irCDgHTtSoYYFxNaro75zze4o+GbVNFWYVa3ifOzQiSfVdsabBsRFSHzVXgxv5kVJLD3QlkkBzVhnWlJikvLu/5e9WT1xFLt4KvKYcTtfgtwy4IYA3qWV3S10Fd+a/RUf5vuvKh04boo1cSnBDhMW232bb9NGCGXpWH4pDB7XbhBy5JSUwAJHkPVf2TTUjscwnj2GH/UwvAg9K8meE8DnVR1fcjIsid6/kkw5WXW4yMWOXBe9ke+42gJmAjezTuwAJ1AAqyuwRL9RjFSP0I04JJRkBBMw2yylP16yJUkt0GlpnbPtHdMC2x86scQ4+Pd3V2zto89aV7m6v8Fmqumu2Fc3guNTN6vsqwd3Sr/XaiutdfbqHCpQhY8TF8sHtXs+agkA9eUag8M4tQ5exJYcorZgCttC5sVkePQ5HLHWBSsV9Mcd5R90+GSXoLABy419nMM4SNFm/tdLLWQTkkFigTUiynRzaX8aFv2ptTt4YhkvB5EMI+I0awoVEcDrDYMkUxen11kcJJbp3u+6zqfIQGRwwxe2J14HujjLjMY=
  - secure: ff7UC3Or+MDCIlakx20gv26SdJMJLdWyo7S+0swxzNe/BSvNxrE7uCfNp9ik5aFUWuCrd1xS1AFmob66Ffcb+3bTTT6B//9QuT6srDImmALa4d0taX0sqb4uNfOqnHBkfhktcb0mhTen2EANgu+S5KJr57fjsBXWqFsGUwe4Paiq6hHsyxolDLXTB/zDf7ZfzfOaiHZH9wvrcMp9EqfiwZY/mGwdkkP5I2ZeOh9jc+JXJ9t4LgbArtSxNYVmiPkzOo8ZSLzrSTqJuin/6n/kVN5bEOu7CTwc7SfG7+fHoW3/5vCsXOO6p1Pj99ECXt7ejtUrVR5PwqNMzL3ZVTEJF0CqPzdqs/IonUKtbBdb94f0+D9N3q+beYJAnt8sf0RZdZ6c/3nsV3ocwFyDf0W4Z0wR9ufzb/LzhCCEjPhSpBbHlIexDEuhvj9PE4wYd2S9Sg/K4SbdZc1F8A/5JN5TdLRrEq67R5hHQez2n0YVzumieG/LkeefdMSAq8VtI+sMYaQACrp9/cj8rChbFOl6T9Klk1HYvipt1TWtu7U/Uu/Bj0j8lzBm3zRWTig2qu4WbT+s3WLDLKWkFAAchD8CFlZI8LH+w5e9sOXUWYEtCw0yVvs7U/5ZvTmIOkf1ZZPYxCkjUgB0I07IEbWqcouu9Em/uFdZLyM6TgUPBKOKALI=
  - secure: alQ4vz44M7BvCxOiLceuG21PRFE5ERrqtEl7AWX086U8q95eCAGIHaC/gF/aRPxXc2RSHxG4JME6sdKiD2Brh1JVLQVz7uUQjrNxyAX7aH/Uhp6P3FeKQxvfJjiTza+KVNtkKLmdWJbAoVkSaNMLtuVGRJanO51qhA5rrGNOVsL62kRkOUOTQQsqmzwU3T6vDvyyg7dB2Z3424uwlOG+la9leZ4sUmqwhj6XrTh//gwbT93ykUVz5xR/PtxwwZrwMyjjQNOEfydHoI3xrLkv5NBqsd1cOn5yn4SUlnP9dcbKsxANfiAKrKOQEeS6PeVyyynurnMXTJSRRCNQzgvxX+ojaQCUmpZrVKDwHGheLzFh9yrLSN/4PyRNGRlUAb6u1pq65mZMyR69+T+7uq8ZXF9PA9XznI3thp/jy4czz1sPGqze48B48R1tnXIjCWlIi182ug09EkbB0zwexVjcqzPElHr528Khty6iImX9Mk5jo7SBSPHnZFuNGus0136FfGBM5lv2Pu6j8NGVy5ID5WyUeDEjJ6ROA00UqP2mnjErCTxd/MG+KG5NiCRSMiRkSFbEbAAQN0skuIwk6DWG2YccSLZ2HQ+CrD0SSB57F/I42cChfuIGKrBKeBZo2BongYmZFPSYuzvKYKaRR1JyI3TlIm2J3XkQh5bKNckhDKw=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- travis version
- export BUILD_NAME=awesomeProject-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export GOPATH=$HOME/gopath
script:
- go build
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
